### ISSUE TITLE
Move tests to their right place

### ISSUE THREAD

**Issue by ma7dev** [approx-ml/approx#18]
**Describe the solution you'd like**
Currently, all of the tests live under `tests/integration/core/test_api.py` but they contain `component tests` for specified components.

**Comment by bushshrub** [comment]
IMO these tests are integration tests seeing as they test our public API

**Comment by xiurobert** [comment]
IMO these tests are integration tests seeing as they test our public API

**Comment by ma7dev** [comment]
Setting `backend` and `device` manually seems to be more correlated testing of the component itself, but they still belong to the API.
